### ISSUE TITLE
Error building windows installer, latest version

### ISSUE THREAD

**Issue by paul-piro** [sindresorhus/grunt-electron#12]
I'm trying to use the latest version with Electron 0.37.6, node 6.1.0, npm 3.8.6 but whatever i try it keeps give me this error:

Running "create-windows-installer:x64" (create-windows-installer) task
Warning: Cannot read property 'link' of undefined Use --force to continue.

I was trying it with Windows 7 which worked well until i updated to latest and OSX with wine

**Comment by sindresorhus** [comment]
This module doesn't create installers.

**Comment by paul-piro** [comment]
create-windows-installer:x64 task it's using grunt-electron which fails, i reverted grunt-electron from 4.0.0 to 2.0.1 and it works so the problem is in this module

**Comment by sindresorhus** [comment]
`grunt-electron` is just a tiny wrapper for electron-packager. Your problem is in that case there.
